
--CLIENTES ATENDIDOS POR EMPLEADOS

CREATE VIEW VW_CLIENTESATENDIDOSPOREMPLEADO AS
SELECT 
E.EmployeeID,
E.FirstName + ' ' + E.LastName AS EMPLEADO,
COUNT(DISTINCT O.CustomerID) AS CLIENTESATENDIDOS
FROM
Orders O
JOIN 
Employees E ON O.EmployeeID = E.EmployeeID
GROUP BY
E.EmployeeID, E.FirstName, E.LastName

select * from VW_CLIENTESATENDIDOSPOREMPLEADO