
--NUMERO DE PEDIDOS PROCESADOS POR EMPLEADO
CREATE VIEW VW_NUMEROPEDIDOSPOREMPLEADO AS
SELECT
E.EmployeeID,
E.FirstName + ' ' + E.LastName AS EMPLEADO,
COUNT(O.OrderID) AS PEDIDOSPROCESADOS
FROM 
Orders O
JOIN
Employees E ON O.EmployeeID = E.EmployeeID
GROUP BY E.EmployeeID,E.FirstName,E.LastName
select * from VW_NUMEROPEDIDOSPOREMPLEADO