
--TOTAL DE VENTAS POR CATEGORIA
CREATE VIEW VW_TOTALVENTASPORCATEGORIA AS
SELECT

C.CategoryName AS CATEGORIA,
COUNT(OD.OrderID) AS TOTALVENTAS
FROM
[Order Details] OD

JOIN
Products P ON OD.ProductID = P.CategoryID
JOIN 
Categories C ON P.CategoryID = C.CategoryID
GROUP BY
C.CategoryName

select * from VW_TOTALVENTASPORCATEGORIA